/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ElQNthibqgr
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"
import { PopoverTrigger, PopoverContent, Popover } from "@/components/ui/popover"
import { Calendar } from "@/components/ui/calendar"
import { AccordionTrigger, AccordionContent, AccordionItem, Accordion } from "@/components/ui/accordion"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function DatePage() {
  return (
    <div className="bg-[#f7f7f7] p-8">
      <div className="max-w-4xl mx-auto">
        <div className="flex justify-between items-center mb-4">
          <Popover>
            <PopoverTrigger asChild>
              <Button className="w-[240px] justify-start text-left font-normal" >
                <CalendarDaysIcon className="mr-1 h-4 w-4 -translate-x-1" />
                Select date
              </Button>
            </PopoverTrigger>
            <PopoverContent align="start" className="w-auto p-0">
              <Calendar initialFocus mode="single" />
            </PopoverContent>
          </Popover>
          <h1 className="text-2xl font-bold text-[#333]">Your Schedule</h1>
        </div>
        <Accordion  type="multiple">
          <AccordionItem value="may-15">
            <AccordionTrigger className="bg-white shadow rounded-lg flex justify-between items-center px-4 py-2 mb-2">
              <div>May 15, 2023</div>
              {/* <ChevronDownIcon className="w-4 h-4 transition-transform" /> */}
            </AccordionTrigger>
            <AccordionContent>
              <Table className="bg-white shadow rounded-lg">
                <TableHeader className="bg-[#eaeaea]">
                  <TableRow>
                    <TableHead className="text-[#555] font-semibold">Time</TableHead>
                    <TableHead className="text-[#555] font-semibold">Event</TableHead>
                    <TableHead className="text-[#555] font-semibold">Details</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow className="border-b">
                    <TableCell className="py-2 text-[#333]">9:00 to 10:00 AM</TableCell>
                    <TableCell className="py-2 text-[#333]">Physics Study Session</TableCell>
                    <TableCell className="py-2 text-[#333]">In-depth concepts review</TableCell>
                  </TableRow>
                  <TableRow className="border-b">
                    <TableCell className="py-2 text-[#333]">10:30 AM to 12:00 PM</TableCell>
                    <TableCell className="py-2 text-[#333]">Anthropology Paper Drafting</TableCell>
                    <TableCell className="py-2 text-[#333]">Draft first section</TableCell>
                  </TableRow>
                  <TableRow className="border-b">
                    <TableCell className="py-2 text-[#333]">4:30 to 5:30 PM</TableCell>
                    <TableCell className="py-2 text-[#333]">Gym Session</TableCell>
                    <TableCell className="py-2 text-[#333]">Cardio and strength training</TableCell>
                  </TableRow>
                  <TableRow className="border-b">
                    <TableCell className="py-2 text-[#333]">6:30 to 8:30 PM</TableCell>
                    <TableCell className="py-2 text-[#333]">Physics Revision</TableCell>
                    <TableCell className="py-2 text-[#333]">Revisit challenging topics</TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="may-16">
            <AccordionTrigger className="bg-white shadow rounded-lg flex justify-between items-center px-4 py-2 mb-2">
              <div>May 16, 2023</div>
              {/* <ChevronDownIcon className="w-4 h-4 transition-transform" /> */}
            </AccordionTrigger>
            <AccordionContent>
              <Table className="bg-white shadow rounded-lg">
                <TableHeader className="bg-[#eaeaea]">
                  <TableRow>
                    <TableHead className="text-[#555] font-semibold">Time</TableHead>
                    <TableHead className="text-[#555] font-semibold">Event</TableHead>
                    <TableHead className="text-[#555] font-semibold">Details</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow className="border-b">
                    <TableCell className="py-2 text-[#333]">2:00 to 4:00 PM</TableCell>
                    <TableCell className="py-2 text-[#333]">Finalize Anthropology Paper</TableCell>
                    <TableCell className="py-2 text-[#333]">Final edits and references check</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="py-2 text-[#333]">6:30 to 9:30 PM</TableCell>
                    <TableCell className="py-2 text-[#333]">Physics Light Review</TableCell>
                    <TableCell className="py-2 text-[#333]">Prepare for next day test</TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </div>
    </div>
  )
}

function CalendarDaysIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
      <path d="M8 14h.01" />
      <path d="M12 14h.01" />
      <path d="M16 14h.01" />
      <path d="M8 18h.01" />
      <path d="M12 18h.01" />
      <path d="M16 18h.01" />
    </svg>
  )
}


function ChevronDownIcon(prop:any) {
  return (
    <svg
      {...prop}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}
